apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - image: okteto.dev/home:latest
        name: homey
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f18a6c28-cda2-4e32-b331-90d2558b1e29"
        - name: Vless_Path
          value: "/s221"
        - name: Vmess_UUID
          value: "f18a6c28-cda2-4e32-b331-90d2558b1e29"
        - name: Vmess_Path
          value: "/s220"
        - name: Share_Path
          value: "/share221"
